[book]
authors = ["Christopher Cordero"]
language = "en"
multilingual = false
src = "src"
title = "Knowledge Base"

[output.html]
additional-css = ["theme/custom.css"]
mathjax-support = true
site-url = "/kb/"
